---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 16.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-blocky"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    securityContext:
      container:
        UMASK: "0022"
        runAsGroup: 568
        runAsUser: 568
      pod:
        fsGroupChangePolicy: OnRootMismatch
    service:
      dns:
        enabled: true
        externalTrafficPolicy: Local
        loadBalancerIP: ${BLOCKY_IP}
        ports:
          dns:
            enabled: true
            port: 53
            protocol: udp
            targetPort: 53
          dnstcp:
            enabled: true
            port: '{{ .Values.service.dns.ports.dns.port }}'
            protocol: tcp
            targetPort: 53
        type: LoadBalancer
      dot:
        enabled: true
        ports:
          dot:
            enabled: true
            port: 853
            protocol: tcp
            targetPort: 853
        type: ClusterIP
      https:
        enabled: true
        ports:
          https:
            enabled: true
            port: 4443
            protocol: https
            targetPort: 4443
        type: ClusterIP
      k8sgateway:
        enabled: true
        ports:
          k8sgateway:
            enabled: true
            port: 5353
            protocol: udp
            targetPort: 5353
        type: ClusterIP
      main:
        enabled: true
        ports:
          main:
            enabled: true
            port: 4000
            protocol: http
            targetPort: 4000
        type: ClusterIP
    bootstrapDns:
      upstream: 192.168.10.3
    blocking:
      whitelist: []
      blacklist: []
      clientGroupsBlock:
        - name: default
          groups:
            - default
    k8sgateway:
      domains:
      - domain: sf.wethecommon.com
        enabled: true
        dnsChallenge:
          enabled: false
          domain: dns01.clouddns.com
      forward:
        enabled: false
        primary: tls://1.1.1.1
        secondary: tls://1.0.0.1
        options:
          - name: tls_servername
            value: cloudflare-dns.com
      ttl: 300
    queryLog:
      type: ""
    configmap:
      dashboard:
        enabled: false
      datasource:
        enabled: false
    cnpg:
      main:
        enabled: false
        cluster:
          instances: 1
          singleNode: true
        backups:
          enabled: false
          revision: ""
        database: blocky
        hibernate: false
        mode: standalone
        monitoring:
          disableDefaultQueries: false
          enablePodMonitor: true
        password: PLACEHOLDERPASSWORD
        pgVersion: 16
        pooler:
          enabled: false
        recovery:
          enabled: false
          revision: ""
          serverName: ""
        user: blocky