apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/traefik-crds/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

