---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: radarr
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            chart: radarr
            version: 23.10.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    install:
        createNamespace: true
        remediation:
          retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
          retries: 3
    uninstall:
        keepHistory: false
    values:
        credentials:
            s3:
                type: s3
                url: "${S3URL}"
                bucket: "radarr${S3PREFIX}"
                accessKey: "${S3ID}"
                secretKey: "${S3KEY}"
                encrKey: "${S3EKEY}"
        TZ: America/Los_Angeles
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 1000
                runAsUser: 1000
            pod:
                fsGroup: 1000
                fsGroupChangePolicy: OnRootMismatch
        metrics:
            main:
               enabled: false
        workload:
            exportarr:
               enabled: false

        ingress:
            main:
                annotations:
                    traefik.frontend.passHostHeader: "false"
                enabled: true
                hosts:
                    - host: radarr.${BASE_DOMAIN}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    hosts:
                        - radarr.${BASE_DOMAIN}
                        secretName: radarr-tls 
                integrations:
                    traefik:
                        enabled: true
                        middlewares:
                            - name: local
                              namespace: traefik
                            - name: bouncer
                              namespace: traefik
                    certManager:
                        enabled: true
                        certificateIssuer: cert
                    homepage:
                        description: Movie Downloader/Manager
                        enabled: true
                        group: Content Management
                        icon: ""
                        name: Radarr
                        widget:
                            custom:
                                key: a1cfd28c2bab49a1b9f6a1ac0c106e45
                            enabled: true
        service:
            main:
                enabled: true
                loadBalancerIP: ${RADARR_IP}
                ports:
                    main:
                        port: 7878
                type: LoadBalancer
                updated: true
        persistence:
            config:
                enabled: true
                targetSelector:
                    main:
                        mountPath: /config
                    exportarr:
                        mountPath: /config
                        readOnly: true
                    media:
                        enabled: true
                        existingClaim: media-nfs-pvc
                        mountPath: "/media"
                    movies:
                        enabled: true
                        existingClaim: media-movies-nfs-pvc
                        mountPath: "/media/movies"
                    downloads:
                        enabled: true
                        existingClaim: downloads-nfs-pvc
                        mountPath: "/usenet"
#                    backup:
#                        enabled: true
#                        mountPath: /config/Backups
#                       volsync:
#                            - name: b2
#                             type: restic
#                              credentials: s3
#                              dest:
#                                cacheCapacity: 10Gi
#                                enabled: true
#                              src:
#                                enabled: true
#                                cacheCapacity: 10Gi

