---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: radarr
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            chart: radarr
            version: 23.11.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    timeout: 20m
    maxHistory: 3
    install:
        createNamespace: true
        remediation:
          retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
          retries: 3
    uninstall:
        keepHistory: false
    values:
        credentials:
            s3:
                type: s3
                url: "${S3URL}"
                bucket: "radarr${S3PREFIX}"
                accessKey: "${S3ID}"
                secretKey: "${S3KEY}"
                encrKey: "${S3EKEY}"
        TZ: America/Los_Angeles
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 1000
                runAsUser: 1000
            pod:
                fsGroup: 1000
                fsGroupChangePolicy: OnRootMismatch
        metrics:
            main:
               enabled: false
        workload:
            exportarr:
               enabled: false

        ingress:
            main:
                enabled: true
                hosts:
                    - host: radarr.${BASE_DOMAIN}
                      paths:
                        - path: /
                          pathType: Prefix
#                tls:
#                    hosts:
#                        - radarr.${BASE_DOMAIN}
#                   secretName: radarr-tls
                integrations:
                    traefik:
                        enabled: true
                        middlewares:
                            - name: local
                              namespace: traefik
                            - name: bouncer
                              namespace: traefik
                        entrypoints:
                            - websecure
                    certManager:
                        enabled: true
                        certificateIssuer: cert
                    homepage:
                        description: Movie Downloader/Manager
                        enabled: true
                        group: Content Management
                        icon: ""
                        name: Radarr
                        widget:
                            custom:
                                key: c0a84c5da5804c47a146ea036e5b961d
                            enabled: true
        service:
            main:
                enabled: true
                type: LoadBalancer
                loadBalancerIP: ${RADARR_IP}
                ports:
                    main:
                        port: 7878

        persistence:
            config:
                enabled: true
                targetSelector:
                    main:
                        mountPath: /config
                    exportarr:
                        mountPath: /config
                        readOnly: true
                    media:
                        autoPermissions:
                            enabled: false
                        enabled: true
                        mountPath: "/media"
                        path: /mnt/Pibbs-Horde/media/data/media
                        readOnly: false
                        server: 192.168.10.123
                        type: nfs
                    movies:
                        autoPermissions:
                            enabled: false
                        enabled: true
                        mountPath: "/media/movies"
                        path: /mnt/Pibbs-Horde/media/data/media/movies
                        readOnly: false
                        server: 192.168.10.123
                        type: nfs
                    downloads:
                        autoPermissions:
                            enabled: false
                        enabled: true
                        mountPath: "/usenet"
                        path: /mnt/Pibbs-Horde/media/data/usenet
                        readOnly: false
                        server: 192.168.10.123
                        type: nfs
                    backup:
                        autoPermissions:
                            enabled: false
                        enabled: true
                        mountPath: "/backups"
                        path: /mnt/Pibbs-Horde/media/data/app_backups/config/Backups
                        readOnly: false
                        server: 192.168.10.123
                        type: nfs
#                    backup:
#                        enabled: true
#                        mountPath: /config/Backups
#                       volsync:
#                            - name: b2
#                             type: restic
#                              credentials: s3
#                              dest:
#                                cacheCapacity: 10Gi
#                                enabled: true
#                              src:
#                                enabled: true
#                                cacheCapacity: 10Gi

