---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: proxmox
    namespace: networking
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 15.2.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: proxmox
    values:
        ingress:
            main:
                enabled: true
                hosts:
                    - host: proxmox.${BASE_DOMAIN}
                      paths:
                        - path: /
                          pathType: Prefix
#                tls:
#                    hosts:
#                        - proxmox.${BASE_DOMAIN}
#                    secretName: proxmox-tls
                integrations:
                    traefik:
                        enabled: true
                        middlewares:
                            - name: local
                              namespace: traefik
                            - name: bouncer
                              namespace: traefik
                        entrypoints:
                            - websecure
                    certManager:
                        enabled: true
                        certificateIssuer: cert
                    homepage:
                        enabled: false
        release_name: proxmox
        service:
            main:
                enabled: true
                externalIP: 192.168.10.30
                ports:
                    main:
                        enabled: true
                        port: 8006
                        protocol: https
                type: ExternalIP
                useSlice: false
        workload:
            main:
                enabled: false
                podSpec:
                    containers:
                        main: {}
