apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 15m
  chart:
    spec:
      chart: crowdsec
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    container_runtime: containerd
    tls:
      enabled: true
      bouncer:
        reflector:
          namespaces: ["traefik"]
    agent:
      acquisition:
        - namespace: traefik
          podName: traefik-*
          program: traefik
      env:
        - name: PARSERS
          value: "crowdsecurity/cri-logs"
        - name: COLLECTIONS
          value: "crowdsecurity/traefik"
        - name: POLL_WITHOUT_INOTIFY
          value: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      securityContext:
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
    lapi:
      dashboard:
        enabled: false
        ingress:
          enabled: false
          annotations:
            cert-manager.io/cluster-issuer: wildcard
            cert-manager.io/private-key-rotation-policy: Always
            meta.helm.sh/release-name: traefik
            meta.helm.sh/release-namespace: traefik
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: 'true'
            traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd,traefik-bouncer@kubernetescrd,traefik-local@kubernetescrd
          host: crowdsec.${BASE_DOMAIN}
      env: {}
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
