apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hRSV2sRTG65EITEHlw+bHOLezrfaJb4yNQO6R2bjlOW6QjzukasqP97Ivfq1r0y6BrmiJsLcf4jhI1ESKtC0oOB75YOQ1CrnTSrTDushemx1zmRT/sL0NB0FUikUL1SRtTQK9ockNUvVpi1YcrL0gXpMHUfF0/bDD6PHAHeXvztCYwbCAAdWwY2mxvIUPboa/gU7h1ssszvs8yqdv+C2kJ3AYGiHHsm29MV5++wHW7TyB8yy9t1eIA3rb7ZHxZc4wzOWj3x6qREsEYxAfl5rNmUzqRlEvx19LfPalJsfQMah5tE1iI8oqKQsrSM/bjGo7mQYQj1y8vefV0kdGccDlQbB8O/1389a/F3xdl17ZHSAOuEohchi2kzYKOyBe7VT,iv:lHqMNT7U+UEDGYq2Z0rsCVMMGsjn/4zq/L9MVAG8rVg=,tag:3OIvFJGpYOyjPZxuREW/CQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:MWutrsBwOQ51GALgAqAT+riowQAIxSBs8p6rNwmQMGy7T/evBwG61XeNGuYXdzee62T36z/kgAduqJNH5VJjN9KupNf0cM0D0MxNjs/C0wpvK4Q6zX2QZ+/gFvZjNNd2hHg071LQZ0iTt+CgniHZjZ7iG1yGf1dvhedZSoDT+zraNkWUiTkodpcugX5pdXER/Tv6495sEVnUAddytXCI6g4rm13hCXU1WiEpVn6b9Ek27n2Duj0UMShKMPyypZeLrJcHt23K+keqRp3Cvg==,iv:jTl+iBdUQK7ysRru0fbtDO+oI887MXosSMh4iPwviMY=,tag:MXZj3edz3Wq/LgfXQ3cFcQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:9uZZpBBO3/oEER44BxDNloiPCWm3dSGBKuLtmVYs0T+EZ46QE0cPNC6AvVVfyLnYQmOHllCQE0GEl4QetSUz596JFQnkGpjF98RqOrr9eNd6W+pHaOrvptyzohfuWHXPFSgmQldMC11MFwu0OsyIe2qf5yZGSAAgtdf9tvQRK9p7isV/znulkUfwsu/SKL6+Ld8VS2vBP5BGtoKlRL7OSwCYCfww8mlBSlcY,iv:qReQ47ZcqJ5HIW9ATYbNhnoCwXZPZADQ/nzTfTXQJkY=,tag:rh1zRQSJvmSRpZSaJ1KZaw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16297mg627a89szg0vhk6frlylz4zjw4wakyqpzkjkuddwgwk4qnsyfkvgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NEZ0WWhTbnI1N3VrdmVU
            WGFreHVqbytla3VEcm4xZHZPcXljam9QZlVRCm15UStSZGlvTTBZaTA4QnNjcUFS
            VnpnbG92TDc2a0dpOFlmTjVuRXlGYzgKLS0tIGo0azQzTXRraFhoeVlGTWliT2M5
            ZVhhY0llc284cFhRRSthTThZSFcrSFEK65gVVzg3qc9MYEFaUe+47gRdfXqypJof
            ZxnIe4UNk5h7RT+KOEoOKc/Irnst1wu8eV1BabRewbfmbgYrTk1Wiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T22:55:25Z"
    mac: ENC[AES256_GCM,data:OY6uLwhAIzvP6WjPrLia6e7DIqvo6DiztJnl1H58xbpvnkEzyAkJFsXJg+5Gda+hrJae3SAjTA3Kqxq+Oe0BhIEKGKNxDA0Q79UtAHggTUBN0AO/YuEMUCHWPmsZF9OMhbWRN00bt+5HtynrAlRtx3glOZ2JBfjmCYHCTKdcXPM=,iv:ocLG//mFj5lr5ofxE9xphTeKovI7t/BmXGZidn6C6IA=,tag:tcXGoFKLm7Pr7542XY+0lA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
