apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:s2GYGdUrV7I4asnK3xCXD4fW08tmosQoQO2TJ9SPiqglK0M7dTPl05efho/lJs1rERwBbWjDJuDCBO55UhV+/+GrrzfFW01Ln0vsm55pR8YQ52V5gQxdABxq6se6ADVwsRSTB4YwhIRXy6g9Wl2VYCrzH+gn7zeO8dwDP2URwluZpgm0xqy9sWOBhWvy+iN2JjOASGpbD7u8kH9xti5HhVGhXLepY1DMHs0C/Fw6ZsjT7KPalLiY9Mfjfan5U8IbtVQL2kUFDUk5qpN7Bfs7d+jyZ6bnW0St/VCldI2n/KqEtG7wTNG6nnZc9v1T1qprJKoNpRe9Vd5XmKCfx42onoaMFBVi5TSZz+1Cnhf0zgm9PHoA9tONyczDq8/UutuR,iv:bhBVIAetn46jqVCuH1yQcoB8RkJUx5IXC3tMyrJHSNg=,tag:Zo54h1PxCENZ+D0zeYTIfA==,type:str]
    identity.pub: ENC[AES256_GCM,data:IuFDb+aDP33RulWlzgPheDaJ12DKB9p3HwxwtdW3+GT9EPPcmNEAZ8GHa7cU7Pc919M6gDin22IVgY7AqilDDk73tG06HrC2OUl2wk1K2cscE6rh7Ciber2SPZd8NXh2FBT27UXi0NuM4JTJ9HdZ3MJ/UL8Ode3ya+bHuDF84Pb6I5mr8xZVjmfX0NCxy9bjFHOFusTCJ0mqc4O5n2axI/GzDam+7QSsAIFhCWKTiE8TpV2VC/1jo03kymeUarDZwEpc556izAXV0jFhsA==,iv:rMQWLsCWcYajgVQJSB4AwFARJ9l3I5+dHMGNIrdIYg8=,tag:/C9gMCeXMRFpnXKUis+4GA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZAm7BZI/n/fw1gZomQq5QWauoWwJOFkL4A+9UTdbiAUcv1nJQj9vFWpXNfFYX81PChZ6+km8ewXQvrjRFUOGdbWfLCzFTk98iFKLO7f9e8szNy2YZEmRbFE7CVRNZ7jE2Eud85d0+UlUT02WZ6+zPEs5XnDZPSdSFCMJTdXMC8POigoo5rvv8lA/oZ5ZInTXwy3hlPBBoTSz+MduWXh0q+E2VyYQOAJfZyP4,iv:Y/wSrrMgSZg1C/SfsjN7CItHJo3ZLP5s2sfozoeNz4M=,tag:UJEEZU3bhIRE129nn+eD8Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16297mg627a89szg0vhk6frlylz4zjw4wakyqpzkjkuddwgwk4qnsyfkvgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMXFrM1pKMS9LdE1nVHl6
            YWFia2EyVjArNW9jNjdpVWlwQWJZbmtXa1ZFClpHQVlRc3E4TUhJYzlFYTVlcURs
            MU9pT2xSMTd6N3hHNDdaQTJITTVZUWcKLS0tIFlqa0habVdTRUVrMllOWTh5VDZR
            MkduQnBqaWVYb0tqNks1VG1FZE5pQ28K8WqVLa3lzLNGHcp1sN5XgZsi4/ndImjM
            AJQAduoh1o6ZTFeL4d0rVYLZvW8SDrzU8ecLEDo2DaHvppxdd07q0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T03:28:15Z"
    mac: ENC[AES256_GCM,data:+T9o4uyUau+fQ/Kfdragdxl8w6UX89T9AO1x5CgAjRcdjO6T7BIoFrDDfM31uCzcplz3fvFWjvq2Ws+Jbb06Xi9/ZKZhESUHXtYkPpHqySVBgF4RjJdt9nLObL2371J4maieRSmGMD1ygxuQu/D21NtST/vXFj9aovhuFSqjH88=,iv:SWyuplFYacesalstqx6exa8/LPSZ9wVsrBLUQiNDd2U=,tag:cPax8+FLY2oHRrN1HbAAng==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
