apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:N3+E2YFm1Z74dCUrRSTcWQVkFhvKFGIY6jmusjYi/qvxu/cmzdMDsinj/dR8r49BJ+k5uYOk+kM4s6jIkRhVmA/Az6mnZxyySAXcrhGKGnDJHZWMGvk4LWuMV4Kry1wnU9AsYfH6hHhJeziV9r6FL7wPCuqjeYAnoqz8tov5ZcdAaqGqW3klY6uaDnqYEyBiz+B+4VN1MAqWcFd7CJofEIW9wJg7wge69F34WJf7RETEtxau3CClzDPfCgTDjSJvhDWwJRQPi2dkrkzHk9GcqSzZPxepnYx79y02vy70qQyeb/0D+16UNTllg62UQ0OUjvppld8hSO7oFYVpyH4s2nm3Alq+w17M1Y6am9jOr/Gv95g/OnjQOlTUATIsessE,iv:MLl2o2yJteok6hL3VP+KAAKH5EjWEEkjexsBuWac+sQ=,tag:bcj/4Eae1mdWYPTAjp47og==,type:str]
    identity.pub: ENC[AES256_GCM,data:uZaxWPK1jQJ0oAACcH0wdu/TAC+oSoKEigkPN0dy4BwC/ME2p+MIX3eIUqWqvWlq7LeB7ZOKyfwgHGEwiho4DnN4/FOsSu1ZD3P+2oBmgNkgG+E3ib5NcSyvXbnNo4lP5nbKSjucF6z22j3tgbFHDqPvGM4Ov3y9nATg7iVdQWSdT4prwXILkyblEDhBcNJ9mZgDyj9RHnBfLxVWll6JNP89+WdWHr4gM/NBCNMzcwD1LSHd0Lcm01yqBlP3QWVEppmYU/lP4QRNqiUq6w==,iv:gXajbNvJei2l0GgdA588zqxL+L9IEp267Y9hXNP+7Q8=,tag:jCqh8n9qc0CkEIkFD9TqaA==,type:str]
    known_hosts: ENC[AES256_GCM,data:BzUsqlXfTai0Pmtl93MON1xDb4EaIj8lYAT7Bi0PR3+D1ucdJKF7tg/byl+asPHUfIdTS3JHtXTZmuwG5mqXx/YQSc71cTHI4Tuni52UtRTLKsPbapc9N5l435h+spsPCYHYmNX8oNIWU9LEoXhovE0dQDioWuWhQvsQuiQ2voX8IskLD85xrOBzQUsJMndZBXfF1Prh6BOrLAQ4Cl/Z9yN1AXTdc4heNubV,iv:iHx48NdSV3szi/DTQVLm6/j51P31Xglk6kRk1UV9rF0=,tag:0EjGYolf0jAl7oQa6lmZOA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16297mg627a89szg0vhk6frlylz4zjw4wakyqpzkjkuddwgwk4qnsyfkvgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bi9CcHExdXllWVBYSjE4
            OEtuUS9VWnV5V1MySkhrWmc1a2xJZEVYaVZRCklxVVM1ZjdUTkFnV2dsa2hiU2Uy
            NisxMU8wam1HeDN4QjZMUGZoT3g2WjQKLS0tIC9VTkJmZnF5M1QzOVNIcno4NVlJ
            TW9lc3JsRHdFUXNmT1N1UytaQVRFZUkKiWWtz2gor1Li/fGE1J+1dvXIozCMHeDX
            G+r4we39M45J2XdUQUH/br7esgzQVI7N1L/H3Ec79zPOwA78aKg+Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T21:53:33Z"
    mac: ENC[AES256_GCM,data:L3I2rYIbpiYRaC1BH6wMn2G1teQIRKzZvp+adAY7+QkuklU6sVApwbtzu/KcE7ZFNsrye5nyXYSwk1v4pyoaZKqyttwUfmmp538ALEoCbccgAR4wG3hx5ZcGe2u6cPwj96YSGCBHk1mM6svNiQk5eRXtuawyfnPR+BKkp9zNwW0=,iv:TMuyexEBapAzRIso0dFQdlTzYadWmUNkDCui/wchPNc=,tag:KVUsmftVWHc9N2nr7Gl8hQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
