apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Au6kQNH/nwX+EMuaVF6Tscs+HwftJxn/1ULPJnwCmPxn7A9bV/6R2mMFTClu2CrtKXDOAfkWpQ+bdfFhTHMrK71zO5lcVpXbzesmsn/QQzJFUD6+IdhFYppvh28Nrq6rc66DteCkCGDbgCvWvzT6Exmr8IdzUwq5mskReiALg79wq1tEPUwEjDMF6+KJVNtSzMCfgqjudiIwJLVPjmfZuNlHfF5I0ed2N/D9ZG0fERfE4JkZM3Kd99nDqxTQYgMISq5htCw+xf1PV7yuzTxR3d9UszNDiqu/S0NKtgzN7jLG8b8qsq9eJW9wuwBOVxzlAsK4LGpSSWYKLx1tYf4uECoUrpEljUFkJWQNe+Yob3SCf64d/uMTKKKeaONE7dja,iv:E2oLjraA0aQIS/BhVUqZQuBi8ZD66McLve/L5wRTjtw=,tag:kcFzq0NmTBQFykecesn1qw==,type:str]
    identity.pub: ENC[AES256_GCM,data:TSMqc6TgHvf3vuFbeinjIxkNHnTAMTJTnq/ofG2Iw4C9hxUEspyM3hWyDdmDbGOemSxjIBgWKOZpJkKeJLnJlj3ERp92DmMtSUtbDJZP5iR3tNrSSzCRIFOZkUfxt8WtIE1YPzhCPvn+sTCxZoDoAzJB90kX+CxXjL2hprF+NnjmISUVGqcZi2drd3jkv0efQZEIjCxqItdv/ueWYmUvDWMGi4/Hsgt5gf2j3V8F42sIqbKRXIh0Bc3YG2EMQSs7zA+pF5yz56mkfQuVpw==,iv:8LWfUCVltE7EU5N0NBWaSQiFZCxxhI30I48/Ceye4NA=,tag:ztJuD2bY2/Wm6ZylL8p+Xg==,type:str]
    known_hosts: ENC[AES256_GCM,data:1HmNFdpXICxKgwZs09o0bS/vGPA7OjcOOt+8s9NndrwJGn8/5KI1QvW4vxUTrPxlUr0xVH8t0A4yYidLpWOrP9LM7rbot8Josya7SvR+iNvhdJ27RGHbmKOMLYwyhglnF78XaGaR1scrPNt8xeckiPja1zwFAZ6aAkHzolan3wEMfx8rtkQTABNLYqDwMJFXXZ8SDVQKsb06Sb3bXJPZt1fYYqNNG4OZj8DQ,iv:xr07s3iG3bbNayB4qnrLbdxalW9v6sBwGzGy0z2WUfw=,tag:5fwBn4aXw0ADwqTHupYkaQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16297mg627a89szg0vhk6frlylz4zjw4wakyqpzkjkuddwgwk4qnsyfkvgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWXNJeFgva1JiOEp1ZWJT
            MUJuZjUzTVlQSnprTUxYU0JpOEVWS1BxTmxrCnBoeXREc3Q4eTduMW9KRDFRRksr
            a25KR0ZoUmIyVjFZbWt6U2h4WTZDSG8KLS0tIGNJTC91OFZMUUFueTMvYjNncmwz
            VTg2Z0VkbzBoeHdMclVSNXBSL0pqL1kKHFXzl3z/3VD4fKUz2TTZ4lI4fd4fSrY+
            aPEoKbeYmD4XS+EvBM9S3d0EAbsH3uo5xKMzft0RwFDSUat3fqJbGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T03:36:19Z"
    mac: ENC[AES256_GCM,data:2rDRXshEOrAPfDT1Ybt/senqZkP0d8IBrJnNiGB1BdxMjzotHbMw3jU3ZOLT054FWm92qDkrEENjDBjoNtfLK/L9QXPIK75C7M5iaIcwuMTySrspw004s/zAudt4v3G01mrJ0PIZz4Fv8s6GqWaa6wloHA62WgYX58mj8uXy5OY=,iv:xTNAgyeP587jRDckRqmWfA/u9eauK2z8eiMh+GgNp4Q=,tag:zUoZW0uzQHtc8ngEH2+OtA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
