apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:st9kFdei+R/JG+lRs6TBn8hxjQn8nTgX/PxgE08hfZQ0PA97ir8JsM7FhIBkKfn+HFCVW9/o9USImCSvrheLRiXynp1zqgy31fzMt6iBSbqwIB+Ep78Lh1KPLk6S82MQxDj4Os7mKpJFkxkefZffDampCTCcNifEQHYgOZ6UnGKW1kHNczn0ZM3iGNGY/w0fTCBj59Yf8kJ/HI6oLgoMtnBS+QuIuG/R2X1qV4J7XMwrHEvJokRbhWiQ7RpkyguzXKPWhNlC9pKyAJ5H4QvegdfWMus/d7y5Rbh5gG/vMoqCAXkaZFjaMEWlrlx1oyGcZZdQx6hbitHRW1nN2F9fi/+Q+/ddHa2wx5SCX9QoMdKC8JH79tChEFCV5+2R4KzI,iv:quWKyLVQzjNSJI7nDOTextYg2ftaslU1XwhV1ICsnXw=,tag:KfTJ+FPkEUgjsgZmBJGXLg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ANoZSEKBUSjVpBa8aggkzgH5pSu/Dv80ur+0RKeSFz5TmvM3r8K7x0CshmOM73Il02LWh6VOBXUy9QvYVlL1AZ9Y6c0UOBfis1ewB/KcPi1Vcqs13lQcDuVJ3zvp6TWSMKsAIOrC8Z101BxwvITuUr7J2xgzf3AzH8A0gAP2MdfwCEOyVrNV7XzG7nBptRyQDWWFSf7x5VeV0Cp+GfVROCqsH79IfQMXVZcwAs6nX622zAkNO0MX+Sf7bhnj9Fpkv7Mt6hjYHYAU8hQQMw==,iv:RoYbHI1gdssCR6R8hIsQ56+K1oLjyRgAr5onMWRswGs=,tag:SC8jNFwcAYKrcSKkH+uAQQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:7Ok2MlFAw7WZCGSRAcf2eeJhKuUNOAtijzRYMG4aiH1xcqOdw3EaQ+tKka5zz9WZq2ZsWCKL92RjGnzLU39nMnyGxFqUMop7l1bmsgjnZDQQl48o+gao/CK1swBtTwoxM3sQ+QkKc7P3S8mr6ZwTsFh+XKerhFqhRHYnoqjOMPRt9r53ApTqjGUkfz4GkOZnHMOoF8erh609NBEopkoextwm2qXFYYpyn2Hg,iv:AvolFOcHBDUoDEdl1r1J94B3kS0JKDhreNa8eGVhU+Y=,tag:cicp4EYmi6NozG6wGukLlg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16297mg627a89szg0vhk6frlylz4zjw4wakyqpzkjkuddwgwk4qnsyfkvgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKblJPTElmRld1SkFiR21Z
            Mmd2TGxzZWxwZ2FHbHB3UGcrS2FMdmh6VW44CkR0c2EzU2NUVUZnd2ZsQnJORS9m
            aUhzdUg0MkthUXVjSUJ5ZTlYVnVhdWMKLS0tIFd6eXBhekw0aVFkUWttY2laMURr
            ZmI2cHFDTVlVZ2RjUEtWeWhQWlRoRzgKnAhdHrejXTEtIsk9obmE8Db3FLuzXSn8
            0wZQMKUoGqvpQTmzBzc4KfjyKttR6mFSj72EmtujJAtZln/TlUvqrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T03:33:02Z"
    mac: ENC[AES256_GCM,data:gX2sLYFqR37wy7Hnzh/yPw++ZE1syFCdfTRht2jDbXMU39J2UiojxmcAvkoXWPTuhvE8WhdLBH2RgCpPcBsoPNS4GYS7uDOohMHYvEj9L4RSNBZT+x1cjyUctGlyv0xzk+tSsvbUyEXyj9UFrIApaeRdLBe1ZiU3dG0xZ1cSM8A=,iv:Q6cKcxrKkTfvidRzdXnpYQRQRUGKOqTWll2tTjBphjk=,tag:VgCbFmacq7D09Wnm0eLzuQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
