apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: descheduler
    namespace: kube-system
spec:
    interval: 15m
    chart:
        spec:
            chart: descheduler
            version: 0.1.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
      mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:

        kind: Deployment
        deschedulerPolicy:
            strategies:
                RemoveDuplicates:
                    enabled: true
                RemovePodsViolatingNodeTaints:
                    enabled: true
                RemovePodsViolatingNodeAffinity:
                    enabled: true
                    params:
                        nodeAffinityType:
                            - requiredDuringSchedulingIgnoredDuringExecution
                RemovePodsViolatingTopologySpreadConstraint:
                    enabled: true
                    params:
                        includeSoftConstraints: true
                RemovePodsViolatingInterPodAntiAffinity:
                    enabled: true
                    params:
                        nodeFit: true
                LowNodeUtilization:
                    enabled: false
                RemoveFailedPods:
                    enabled: true
                    params:
                        failedPods:
                            includingInitContainers: true
                            excludeOwnerKinds:
                                - Job
                            minPodLifetimeSeconds: 3600
                RemovePodsHavingTooManyRestarts:
                    enabled: true
                    params:
                        podsHavingTooManyRestarts:
                            podRestartThreshold: 100
                            includingInitContainers: true
