---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: roon
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 15.2.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: roon
    values:
        ingress:
            main:
                annotations:
                    traefik.frontend.passHostHeader: "false"
                enabled: true
                hosts:
                    - host: roon.${BASE_DOMAIN}
                      paths:
                        - path: /
                          pathType: Prefix
#                tls:
#                    hosts:
#                        - roon.${BASE_DOMAIN}
#                    secretName: roon-tls
                integrations:
                    traefik:
                        enabled: true
                        middlewares:
                            - name: local
                              namespace: traefik
                            - name: bouncer
                              namespace: traefik
                    certManager:
                        certificateIssuer: cert
                        enabled: true
                    homepage:
                        enabled: false
        release_name: roon
        service:
            main:
                enabled: true
                externalIP: 192.168.10.101
                ports:
                    main:
                        enabled: true
                        port: 80
                        protocol: http
                type: ExternalIP
                useSlice: false
        workload:
            main:
                enabled: false
                podSpec:
                    containers:
                        main: {}
