# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 29.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    logs:
      general:
        level: ERROR
        format: json
      access:
        enabled: true
        operator:
          register: true
    persistence:
      crowdsec-bouncer-tls:
        enabled: '{{ if .Values.middlewares.bouncer }}true{{ else }}false{{ end }}'
        expandObjectName: false
        mountPath: /etc/traefik/crowdsec-certs
        objectName: crowdsec-bouncer-tls
        type: secret
      plugins:
        enabled: true
        mountPath: /plugins-storage
        type: emptyDir
    podOptions:
      automountServiceAccountToken: true
    portalhook:
      enabled: true
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: true
    release_name: traefik
    resources: {}
    securityContext:
      container:
        UMASK: "0022"
        runAsGroup: 568
        runAsUser: 568
      pod:
        fsGroupChangePolicy: OnRootMismatch
    defaultCertificate: ""
    service:
      main:
        enabled: true
        loadBalancerIP: ${TRAEFIKDASHBOARD_IP}
        ports:
            main:
                forwardedHeaders:
                    enabled: false
                port: 9000
                protocol: http
                proxyProtocol:
                    enabled: false
                targetPort: 9000
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}
        externalTrafficPolicy: Local
        ports:
          web:
            enabled: true
            port: 80
            protocol: http
            redirectTo: websecure
          websecure:
            enabled: true
            port: 443
            protocol: https
            forwardedHeaders:
              enabled: false
              trustedIPs: []
              insecureMode: false
            proxyProtocol:
              enabled: false
              trustedIPs: []
              insecureMode: false
    tlsOptions:
      default:
        cipherSuites:
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
          - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
          - TLS_AES_128_GCM_SHA256
          - TLS_AES_256_GCM_SHA384
          - TLS_CHACHA20_POLY1305_SHA256
        curvePreferences:
          - CurveP521
          - CurveP384
          - X25519
        minVersion: VersionTLS12
        sniStrict: false
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: false
            middlewares:
              - name: local
                namespace: traefik
              - name: bouncer
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: cert
        hosts:
          - host: traefik.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    middlewares:
      ipWhiteList:
        - name: local
          sourceRange:
            - 172.16.0.0/16
            - 172.17.0.0/16
            - 192.168.10.0/24
            - 192.168.20.0/24
            - 192.168.30.0/24
      bouncer:
        - name: bouncer
          enabled: true
          logLevel: INFO
          format: json
          noColor: true
          crowdsecMode: stream
          crowdsecLapiHost: crowdsec-service.crowdsec:8080
          forwardedHeadersTrustedIPs: []
          clientTrustedIPs:
            - 172.16.0.0/16
            - 172.17.0.0/16
            - 192.168.10.0/24
            - 192.168.20.0/24
            - 192.168.30.0/24
          crowdsecLapiTLSCertificateAuthorityFile: /etc/traefik/crowdsec-certs/ca.crt
          crowdsecLapiTLSCertificateBouncerFile: /etc/traefik/crowdsec-certs/tls.crt
          crowdsecLapiTLSCertificateBouncerKeyFile: /etc/traefik/crowdsec-certs/tls.key
