apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clusterissuer
  namespace: cert-manager
spec:
  interval: 15m
  chart:
    spec:
      chart: clusterissuer
      version: 9.2.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    clusterIssuer:
      ACME:
        - name: cert
          enabled: true
          email: "${DOCKERHUB_USER}"
          server: https://acme-v02.api.letsencrypt.org/directory
          type: cloudflare
          cfapitoken: "${CLOUDFLARE_API_TOKEN}"
      selfSigned:
        enabled: true
        name: "selfsigned"
    clusterCertificates:
      # Namespaces in which the certificates must be available
      # Accepts comma-separated regex expressions
      # replicationNamespaces: '.*'
      # replicationNamespaces: 'ix-.*'
      certificates:
        - name: wildcard
          enabled: true
          certificateIssuer: cert
          hosts:
            - wethecommon.com
            - '*.wethecommon.com'
