---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: usenet-nfs-pv
  namespace: media
spec:
  storageClassName: usenet-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.123
    path: "/mnt/Pibbs-Horde/media/data/usenet"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usenet-nfs-pvc
  namespace: media
spec:
  storageClassName: usenet-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
