---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
  namespace: media
spec:
  storageClassName: media-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.123
    path: "/mnt/Pibbs-Horde/media/data/media/"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
  namespace: media
spec:
  storageClassName: media-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tv-nfs-pv
  namespace: media
spec:
  storageClassName: media-tv-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.123
    path: "/mnt/Pibbs-Horde/media/data/media/tv/"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tv-nfs-pvc
  namespace: media
spec:
  storageClassName: media-tv-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies-nfs-pv
  namespace: media
spec:
  storageClassName: media-movies-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.123
    path: "/mnt/Pibbs-Horde/media/data/media/movies/"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies-nfs-pvc
  namespace: media
spec:
  storageClassName: media-movies-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-music-nfs-pv
  namespace: media
spec:
  storageClassName: media-music-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.123
    path: "/mnt/Pibbs-Horde/media/data/media/music/"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-music-nfs-pvc
  namespace: media
spec:
  storageClassName: media-music-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-books-nfs-pv
  namespace: media
spec:
  storageClassName: media-books-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.123
    path: "/mnt/Pibbs-Horde/media/data/media/books/"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-books-nfs-pvc
  namespace: media
spec:
  storageClassName: media-books-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-comics-nfs-pv
  namespace: media
spec:
  storageClassName: media-comics-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.123
    path: "/mnt/Pibbs-Horde/media/data/media/comics/"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-comics-nfs-pvc
  namespace: media
spec:
  storageClassName: media-comics-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
